#!/bin/bash
set -o errexit
set -o nounset

# helper functions
function progress () { echo -e " \033[1;34m➜\033[0m  $@"; }
function warning ()  { echo -e " \033[1;33m!\033[0m  $@"; }
function success ()  { echo -e " \033[1;32m✔\033[0m  $@"; }
function package ()  { sudo apt-get -qq install "$@"; }
function repo () { sudo add-apt-repository --yes --update "$@" > /dev/null 2>&1; }

# fetch url checksum target
function fetch () {
    progress "fetching $1"
    curl --create-dirs --fail --show-error --silent --output "$3" --url "$1"
    echo "$2  $3" | sha256sum --strict --check --quiet
}

# missing command
function missing () {
    ! command -v $1 >/dev/null 2>&1
}

# apply yadm specific .gitignore
# https://github.com/TheLocehiliosan/yadm/issues/98
progress "apply patterns from .yadm/yadm.gitignore"
ln --force --symbolic "/home/$USER/.yadm/yadm.gitignore" "/home/$USER/.yadm/repo.git/info/exclude"

for each in /home/$USER/.yadm/bootstrap.d/*; do
    [ -e "$each" ] || continue  # no bootstrap files present
    progress "applying $(basename $each)"
    source $each
done

success "$(hostname) bootstrapped"
